# Copyright (C) 2017-2020 CZ.NIC, z.s.p.o. <https://www.nic.cz>

image: debian:10

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apt-get --quiet update
  - apt-get install -y make
  - make prepare-dev

stages:
  - test
  - build


test:
  stage: test
  script:
    - make test

lint:
  stage: test
  script:
    - make lint


build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
    - ./*.deb
    - ./*.rpm
    - ./*.tar

build-docker:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  tags:
    - dind
  before_script:
    - ''
  script:
    - docker build .
